# Generated by Django 5.1.1 on 2024-09-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cocinero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cocinero', models.IntegerField(max_length=100)),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='comensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField(max_length=100)),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_comida', models.IntegerField(max_length=100)),
                ('nombre_platillo', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='contiene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contiene', models.IntegerField(max_length=100)),
                ('tipo', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_entrega', models.IntegerField(max_length=100)),
                ('tipo_entrega', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ingredientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ingredientes', models.IntegerField(max_length=100)),
                ('tipo_ingredientes', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_inventario', models.IntegerField(max_length=100)),
                ('procedencia_ingredientes', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_menu', models.IntegerField(max_length=100)),
                ('tipo_comida', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='mesero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mesero', models.IntegerField(max_length=100)),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pedido', models.IntegerField(max_length=100)),
                ('plato', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='prerara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_preparacion', models.IntegerField(max_length=100)),
                ('receta', models.CharField(max_length=60)),
            ],
        ),
    ]
